version: '3'
services:
  postgres-activities:
    build: ./src/docker/postgres-activities
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  auth_server:
    build: ./src/docker/auth_server
    ports:
      - "5050:5050"
    volumes:
      - ./data:/opt/auth_server/data
  custom_http_server:
    build: ./src/docker/custom_http_server
    ports:
      - "8090:8090"
    volumes:
      - ./www:/opt/custom_http_server/www